// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package db

import (
	"context"
)

const accountGetCredentialsByEmail = `-- name: AccountGetCredentialsByEmail :one
SELECT id, password_hash FROM users WHERE email = ?
`

type AccountGetCredentialsByEmailRow struct {
	ID           string
	PasswordHash string
}

// Login lookup. users.email is COLLATE NOCASE, so the match is case-insensitive.
func (q *Queries) AccountGetCredentialsByEmail(ctx context.Context, email string) (AccountGetCredentialsByEmailRow, error) {
	row := q.db.QueryRowContext(ctx, accountGetCredentialsByEmail, email)
	var i AccountGetCredentialsByEmailRow
	err := row.Scan(&i.ID, &i.PasswordHash)
	return i, err
}

const accountGetPasswordHash = `-- name: AccountGetPasswordHash :one
SELECT password_hash FROM users WHERE id = ?
`

func (q *Queries) AccountGetPasswordHash(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, accountGetPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}
