// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package db

import (
	"context"
)

const activityInsert = `-- name: ActivityInsert :exec

INSERT INTO ticket_activity (id, ticket_id, actor_type, actor_id, action, changes, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type ActivityInsertParams struct {
	ID        string
	TicketID  string
	ActorType string
	ActorID   string
	Action    string
	Changes   string
	CreatedAt string
}

// Activity queries. Every name carries the Activity prefix.
func (q *Queries) ActivityInsert(ctx context.Context, arg ActivityInsertParams) error {
	_, err := q.db.ExecContext(ctx, activityInsert,
		arg.ID,
		arg.TicketID,
		arg.ActorType,
		arg.ActorID,
		arg.Action,
		arg.Changes,
		arg.CreatedAt,
	)
	return err
}

const activityList = `-- name: ActivityList :many
SELECT a.id, a.ticket_id, a.actor_type, a.actor_id, a.action, a.changes, a.created_at,
       u.display_name AS user_name, tk.name AS token_name, ou.display_name AS owner_name
FROM ticket_activity a
LEFT JOIN users u ON a.actor_type = 'user' AND u.id = a.actor_id
LEFT JOIN api_tokens tk ON a.actor_type = 'api_token' AND tk.id = a.actor_id
LEFT JOIN users ou ON ou.id = tk.user_id
WHERE a.ticket_id = ?1
  AND (CAST(?2 AS INTEGER) = 0
       OR a.created_at < CAST(?3 AS TEXT)
       OR (a.created_at = CAST(?3 AS TEXT) AND a.id < CAST(?4 AS TEXT)))
ORDER BY a.created_at DESC, a.id DESC
LIMIT ?5
`

type ActivityListParams struct {
	TicketID        string
	HasCursor       int64
	CursorCreatedAt string
	CursorID        string
	RowLimit        int64
}

type ActivityListRow struct {
	ID        string
	TicketID  string
	ActorType string
	ActorID   string
	Action    string
	Changes   string
	CreatedAt string
	UserName  *string
	TokenName *string
	OwnerName *string
}

// Newest first by (created_at, id); keyset in expanded OR form. Names via LEFT JOINs.
func (q *Queries) ActivityList(ctx context.Context, arg ActivityListParams) ([]ActivityListRow, error) {
	rows, err := q.db.QueryContext(ctx, activityList,
		arg.TicketID,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityListRow
	for rows.Next() {
		var i ActivityListRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.Changes,
			&i.CreatedAt,
			&i.UserName,
			&i.TokenName,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activitySeedListRaw = `-- name: ActivitySeedListRaw :many
SELECT id, ticket_id, actor_type, actor_id, "action", changes, created_at FROM ticket_activity WHERE ticket_id = ? ORDER BY created_at, id
`

// Test only: raw activity rows of a ticket (including soft-deleted tickets), oldest first.
func (q *Queries) ActivitySeedListRaw(ctx context.Context, ticketID string) ([]TicketActivity, error) {
	rows, err := q.db.QueryContext(ctx, activitySeedListRaw, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketActivity
	for rows.Next() {
		var i TicketActivity
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.ActorType,
			&i.ActorID,
			&i.Action,
			&i.Changes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
