// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authz.sql

package db

import (
	"context"
)

const getProjectForUser = `-- name: GetProjectForUser :one
SELECT p.id, p.key, p.name, p.description, p.next_ticket_number, p.created_by,
       p.archived_at, p.created_at, p.updated_at, m.role AS member_role
FROM projects p
JOIN project_members m ON m.project_id = p.id AND m.user_id = ?1
WHERE (CAST(?2 AS TEXT) <> '' AND p.id = CAST(?2 AS TEXT))
   OR (CAST(?3 AS TEXT) <> '' AND p.key = CAST(?3 AS TEXT))
`

type GetProjectForUserParams struct {
	UserID string
	RefID  string
	RefKey string
}

type GetProjectForUserRow struct {
	ID               string
	Key              string
	Name             string
	Description      string
	NextTicketNumber int64
	CreatedBy        string
	ArchivedAt       *string
	CreatedAt        string
	UpdatedAt        string
	MemberRole       string
}

// Resolves a project by id OR key together with the user's membership in one query.
// Pass the ULID in ref_id (or "") and the uppercased key in ref_key (or "").
// No row means unknown project and non-member alike.
func (q *Queries) GetProjectForUser(ctx context.Context, arg GetProjectForUserParams) (GetProjectForUserRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectForUser, arg.UserID, arg.RefID, arg.RefKey)
	var i GetProjectForUserRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.NextTicketNumber,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MemberRole,
	)
	return i, err
}

const locateComment = `-- name: LocateComment :one
SELECT c.id, c.ticket_id, c.author_type, c.author_id, t.project_id, t.number AS ticket_number, p.key AS project_key
FROM comments c
JOIN tickets t ON t.id = c.ticket_id
JOIN projects p ON p.id = t.project_id
WHERE c.id = ? AND c.deleted_at IS NULL AND t.deleted_at IS NULL
`

type LocateCommentRow struct {
	ID           string
	TicketID     string
	AuthorType   string
	AuthorID     string
	ProjectID    string
	TicketNumber int64
	ProjectKey   string
}

// Owning ticket and project of a live comment on a live ticket.
func (q *Queries) LocateComment(ctx context.Context, id string) (LocateCommentRow, error) {
	row := q.db.QueryRowContext(ctx, locateComment, id)
	var i LocateCommentRow
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AuthorType,
		&i.AuthorID,
		&i.ProjectID,
		&i.TicketNumber,
		&i.ProjectKey,
	)
	return i, err
}

const locateLabel = `-- name: LocateLabel :one
SELECT id, project_id FROM labels WHERE id = ?
`

type LocateLabelRow struct {
	ID        string
	ProjectID string
}

func (q *Queries) LocateLabel(ctx context.Context, id string) (LocateLabelRow, error) {
	row := q.db.QueryRowContext(ctx, locateLabel, id)
	var i LocateLabelRow
	err := row.Scan(&i.ID, &i.ProjectID)
	return i, err
}

const locateTicketByID = `-- name: LocateTicketByID :one
SELECT t.id, t.project_id, t.number, p.key AS project_key
FROM tickets t JOIN projects p ON p.id = t.project_id
WHERE t.id = ? AND t.deleted_at IS NULL
`

type LocateTicketByIDRow struct {
	ID         string
	ProjectID  string
	Number     int64
	ProjectKey string
}

// Owning project of a live (not soft-deleted) ticket.
func (q *Queries) LocateTicketByID(ctx context.Context, id string) (LocateTicketByIDRow, error) {
	row := q.db.QueryRowContext(ctx, locateTicketByID, id)
	var i LocateTicketByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.ProjectKey,
	)
	return i, err
}

const locateTicketByRef = `-- name: LocateTicketByRef :one
SELECT t.id, t.project_id, t.number, p.key AS project_key
FROM tickets t JOIN projects p ON p.id = t.project_id
WHERE p.key = ? AND t.number = ? AND t.deleted_at IS NULL
`

type LocateTicketByRefParams struct {
	Key    string
	Number int64
}

type LocateTicketByRefRow struct {
	ID         string
	ProjectID  string
	Number     int64
	ProjectKey string
}

// Same, by project key (uppercase) and ticket number.
func (q *Queries) LocateTicketByRef(ctx context.Context, arg LocateTicketByRefParams) (LocateTicketByRefRow, error) {
	row := q.db.QueryRowContext(ctx, locateTicketByRef, arg.Key, arg.Number)
	var i LocateTicketByRefRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.ProjectKey,
	)
	return i, err
}
