// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
)

const commentGetView = `-- name: CommentGetView :one
SELECT c.id, c.ticket_id, c.author_type, c.author_id, c.body, c.created_at, c.edited_at,
       u.display_name AS user_name, tk.name AS token_name, ou.display_name AS owner_name
FROM comments c
LEFT JOIN users u ON c.author_type = 'user' AND u.id = c.author_id
LEFT JOIN api_tokens tk ON c.author_type = 'api_token' AND tk.id = c.author_id
LEFT JOIN users ou ON ou.id = tk.user_id
WHERE c.id = ? AND c.deleted_at IS NULL
`

type CommentGetViewRow struct {
	ID         string
	TicketID   string
	AuthorType string
	AuthorID   string
	Body       string
	CreatedAt  string
	EditedAt   *string
	UserName   *string
	TokenName  *string
	OwnerName  *string
}

// A live comment with resolved author names (LEFT JOINs: missing rows give NULL names).
func (q *Queries) CommentGetView(ctx context.Context, id string) (CommentGetViewRow, error) {
	row := q.db.QueryRowContext(ctx, commentGetView, id)
	var i CommentGetViewRow
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AuthorType,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.EditedAt,
		&i.UserName,
		&i.TokenName,
		&i.OwnerName,
	)
	return i, err
}

const commentInsert = `-- name: CommentInsert :exec

INSERT INTO comments (id, ticket_id, author_type, author_id, body, created_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CommentInsertParams struct {
	ID         string
	TicketID   string
	AuthorType string
	AuthorID   string
	Body       string
	CreatedAt  string
}

// Comment queries. Every name carries the Comment prefix.
func (q *Queries) CommentInsert(ctx context.Context, arg CommentInsertParams) error {
	_, err := q.db.ExecContext(ctx, commentInsert,
		arg.ID,
		arg.TicketID,
		arg.AuthorType,
		arg.AuthorID,
		arg.Body,
		arg.CreatedAt,
	)
	return err
}

const commentListAsc = `-- name: CommentListAsc :many
SELECT c.id, c.ticket_id, c.author_type, c.author_id, c.body, c.created_at, c.edited_at,
       u.display_name AS user_name, tk.name AS token_name, ou.display_name AS owner_name
FROM comments c
LEFT JOIN users u ON c.author_type = 'user' AND u.id = c.author_id
LEFT JOIN api_tokens tk ON c.author_type = 'api_token' AND tk.id = c.author_id
LEFT JOIN users ou ON ou.id = tk.user_id
WHERE c.ticket_id = ?1 AND c.deleted_at IS NULL
  AND (CAST(?2 AS INTEGER) = 0
       OR c.created_at > CAST(?3 AS TEXT)
       OR (c.created_at = CAST(?3 AS TEXT) AND c.id > CAST(?4 AS TEXT)))
ORDER BY c.created_at, c.id
LIMIT ?5
`

type CommentListAscParams struct {
	TicketID        string
	HasCursor       int64
	CursorCreatedAt string
	CursorID        string
	RowLimit        int64
}

type CommentListAscRow struct {
	ID         string
	TicketID   string
	AuthorType string
	AuthorID   string
	Body       string
	CreatedAt  string
	EditedAt   *string
	UserName   *string
	TokenName  *string
	OwnerName  *string
}

// Oldest first by (created_at, id), excluding deleted; keyset in expanded OR form.
func (q *Queries) CommentListAsc(ctx context.Context, arg CommentListAscParams) ([]CommentListAscRow, error) {
	rows, err := q.db.QueryContext(ctx, commentListAsc,
		arg.TicketID,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentListAscRow
	for rows.Next() {
		var i CommentListAscRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.AuthorType,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.EditedAt,
			&i.UserName,
			&i.TokenName,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const commentListNewest = `-- name: CommentListNewest :many
SELECT c.id, c.ticket_id, c.author_type, c.author_id, c.body, c.created_at, c.edited_at,
       u.display_name AS user_name, tk.name AS token_name, ou.display_name AS owner_name
FROM comments c
LEFT JOIN users u ON c.author_type = 'user' AND u.id = c.author_id
LEFT JOIN api_tokens tk ON c.author_type = 'api_token' AND tk.id = c.author_id
LEFT JOIN users ou ON ou.id = tk.user_id
WHERE c.ticket_id = ?1 AND c.deleted_at IS NULL
ORDER BY c.created_at DESC, c.id DESC
LIMIT ?2
`

type CommentListNewestParams struct {
	TicketID string
	RowLimit int64
}

type CommentListNewestRow struct {
	ID         string
	TicketID   string
	AuthorType string
	AuthorID   string
	Body       string
	CreatedAt  string
	EditedAt   *string
	UserName   *string
	TokenName  *string
	OwnerName  *string
}

// Newest first (the caller flips to oldest first); used by Latest(n).
func (q *Queries) CommentListNewest(ctx context.Context, arg CommentListNewestParams) ([]CommentListNewestRow, error) {
	rows, err := q.db.QueryContext(ctx, commentListNewest, arg.TicketID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentListNewestRow
	for rows.Next() {
		var i CommentListNewestRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.AuthorType,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.EditedAt,
			&i.UserName,
			&i.TokenName,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const commentSeedDeleteToken = `-- name: CommentSeedDeleteToken :exec
DELETE FROM api_tokens WHERE id = ?
`

// Test only: remove a token row so author names fall back to "deleted token".
func (q *Queries) CommentSeedDeleteToken(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, commentSeedDeleteToken, id)
	return err
}

const commentSeedDeleteUser = `-- name: CommentSeedDeleteUser :exec
DELETE FROM users WHERE id = ?
`

// Test only: remove a user row so author names fall back to "deleted user".
func (q *Queries) CommentSeedDeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, commentSeedDeleteUser, id)
	return err
}

const commentSeedGetRaw = `-- name: CommentSeedGetRaw :one
SELECT id, ticket_id, author_type, author_id, body, created_at, edited_at, deleted_at FROM comments WHERE id = ?
`

// Test only: a comment row including soft-deleted ones.
func (q *Queries) CommentSeedGetRaw(ctx context.Context, id string) (Comment, error) {
	row := q.db.QueryRowContext(ctx, commentSeedGetRaw, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AuthorType,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const commentSeedSetRole = `-- name: CommentSeedSetRole :exec
UPDATE project_members SET role = ? WHERE project_id = ? AND user_id = ?
`

type CommentSeedSetRoleParams struct {
	Role      string
	ProjectID string
	UserID    string
}

// Test only: change a member's role directly (e.g. demote a comment author).
func (q *Queries) CommentSeedSetRole(ctx context.Context, arg CommentSeedSetRoleParams) error {
	_, err := q.db.ExecContext(ctx, commentSeedSetRole, arg.Role, arg.ProjectID, arg.UserID)
	return err
}

const commentSoftDelete = `-- name: CommentSoftDelete :exec
UPDATE comments SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL
`

type CommentSoftDeleteParams struct {
	DeletedAt *string
	ID        string
}

func (q *Queries) CommentSoftDelete(ctx context.Context, arg CommentSoftDeleteParams) error {
	_, err := q.db.ExecContext(ctx, commentSoftDelete, arg.DeletedAt, arg.ID)
	return err
}

const commentUpdateBody = `-- name: CommentUpdateBody :exec
UPDATE comments SET body = ?, edited_at = ? WHERE id = ?
`

type CommentUpdateBodyParams struct {
	Body     string
	EditedAt *string
	ID       string
}

func (q *Queries) CommentUpdateBody(ctx context.Context, arg CommentUpdateBodyParams) error {
	_, err := q.db.ExecContext(ctx, commentUpdateBody, arg.Body, arg.EditedAt, arg.ID)
	return err
}
