// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package db

import (
	"context"
)

const labelDelete = `-- name: LabelDelete :exec
DELETE FROM labels WHERE id = ?
`

func (q *Queries) LabelDelete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, labelDelete, id)
	return err
}

const labelGet = `-- name: LabelGet :one
SELECT id, project_id, name, color FROM labels WHERE id = ?
`

func (q *Queries) LabelGet(ctx context.Context, id string) (Label, error) {
	row := q.db.QueryRowContext(ctx, labelGet, id)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
	)
	return i, err
}

const labelInsert = `-- name: LabelInsert :one
INSERT INTO labels (id, project_id, name, color) VALUES (?, ?, ?, ?)
RETURNING id, project_id, name, color
`

type LabelInsertParams struct {
	ID        string
	ProjectID string
	Name      string
	Color     string
}

func (q *Queries) LabelInsert(ctx context.Context, arg LabelInsertParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, labelInsert,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Color,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
	)
	return i, err
}

const labelList = `-- name: LabelList :many
SELECT id, project_id, name, color FROM labels WHERE project_id = ? ORDER BY name COLLATE NOCASE, id
`

func (q *Queries) LabelList(ctx context.Context, projectID string) ([]Label, error) {
	rows, err := q.db.QueryContext(ctx, labelList, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const labelNameTaken = `-- name: LabelNameTaken :one
SELECT EXISTS (
  SELECT 1 FROM labels
  WHERE project_id = ?1 AND name = ?2 AND id <> ?3
)
`

type LabelNameTakenParams struct {
	ProjectID string
	Name      string
	ExcludeID string
}

// True when another label (id <> exclude_id; pass ” for none) of the project has the name (NOCASE column).
func (q *Queries) LabelNameTaken(ctx context.Context, arg LabelNameTakenParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, labelNameTaken, arg.ProjectID, arg.Name, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const labelUpdate = `-- name: LabelUpdate :one
UPDATE labels SET name = ?, color = ? WHERE id = ?
RETURNING id, project_id, name, color
`

type LabelUpdateParams struct {
	Name  string
	Color string
	ID    string
}

func (q *Queries) LabelUpdate(ctx context.Context, arg LabelUpdateParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, labelUpdate, arg.Name, arg.Color, arg.ID)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
	)
	return i, err
}
