// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package db

import (
	"context"
)

const memberClearAssignee = `-- name: MemberClearAssignee :execrows
UPDATE tickets SET assignee_id = NULL WHERE project_id = ? AND assignee_id = ?
`

type MemberClearAssigneeParams struct {
	ProjectID  string
	AssigneeID *string
}

// Unassigns the user from every ticket of the project, soft-deleted ones included.
func (q *Queries) MemberClearAssignee(ctx context.Context, arg MemberClearAssigneeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, memberClearAssignee, arg.ProjectID, arg.AssigneeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const memberCountOwners = `-- name: MemberCountOwners :one
SELECT COUNT(*) FROM project_members WHERE project_id = ? AND role = 'owner'
`

func (q *Queries) MemberCountOwners(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, memberCountOwners, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const memberDelete = `-- name: MemberDelete :execrows
DELETE FROM project_members WHERE project_id = ? AND user_id = ?
`

type MemberDeleteParams struct {
	ProjectID string
	UserID    string
}

func (q *Queries) MemberDelete(ctx context.Context, arg MemberDeleteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, memberDelete, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const memberGet = `-- name: MemberGet :one
SELECT m.user_id, u.email, u.display_name, m.role, m.created_at
FROM project_members m
JOIN users u ON u.id = m.user_id
WHERE m.project_id = ? AND m.user_id = ?
`

type MemberGetParams struct {
	ProjectID string
	UserID    string
}

type MemberGetRow struct {
	UserID      string
	Email       string
	DisplayName string
	Role        string
	CreatedAt   string
}

func (q *Queries) MemberGet(ctx context.Context, arg MemberGetParams) (MemberGetRow, error) {
	row := q.db.QueryRowContext(ctx, memberGet, arg.ProjectID, arg.UserID)
	var i MemberGetRow
	err := row.Scan(
		&i.UserID,
		&i.Email,
		&i.DisplayName,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const memberInsert = `-- name: MemberInsert :exec
INSERT INTO project_members (project_id, user_id, role, created_at)
VALUES (?, ?, ?, ?)
`

type MemberInsertParams struct {
	ProjectID string
	UserID    string
	Role      string
	CreatedAt string
}

func (q *Queries) MemberInsert(ctx context.Context, arg MemberInsertParams) error {
	_, err := q.db.ExecContext(ctx, memberInsert,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const memberInsertActivity = `-- name: MemberInsertActivity :exec
INSERT INTO ticket_activity (id, ticket_id, actor_type, actor_id, action, changes, created_at)
VALUES (?, ?, ?, ?, 'assigned', ?, ?)
`

type MemberInsertActivityParams struct {
	ID        string
	TicketID  string
	ActorType string
	ActorID   string
	Changes   string
	CreatedAt string
}

func (q *Queries) MemberInsertActivity(ctx context.Context, arg MemberInsertActivityParams) error {
	_, err := q.db.ExecContext(ctx, memberInsertActivity,
		arg.ID,
		arg.TicketID,
		arg.ActorType,
		arg.ActorID,
		arg.Changes,
		arg.CreatedAt,
	)
	return err
}

const memberList = `-- name: MemberList :many
SELECT m.user_id, u.email, u.display_name, m.role, m.created_at
FROM project_members m
JOIN users u ON u.id = m.user_id
WHERE m.project_id = ?
ORDER BY CASE m.role WHEN 'owner' THEN 0 ELSE 1 END, lower(u.display_name), m.user_id
`

type MemberListRow struct {
	UserID      string
	Email       string
	DisplayName string
	Role        string
	CreatedAt   string
}

// Owners first, then display name (case-insensitive), then user id.
func (q *Queries) MemberList(ctx context.Context, projectID string) ([]MemberListRow, error) {
	rows, err := q.db.QueryContext(ctx, memberList, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberListRow
	for rows.Next() {
		var i MemberListRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberListLiveAssignedTickets = `-- name: MemberListLiveAssignedTickets :many
SELECT id FROM tickets
WHERE project_id = ? AND assignee_id = ? AND deleted_at IS NULL
ORDER BY id
`

type MemberListLiveAssignedTicketsParams struct {
	ProjectID  string
	AssigneeID *string
}

// Live tickets of the project currently assigned to the user (for the activity rows).
func (q *Queries) MemberListLiveAssignedTickets(ctx context.Context, arg MemberListLiveAssignedTicketsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, memberListLiveAssignedTickets, arg.ProjectID, arg.AssigneeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memberUpdateRole = `-- name: MemberUpdateRole :execrows
UPDATE project_members SET role = ? WHERE project_id = ? AND user_id = ?
`

type MemberUpdateRoleParams struct {
	Role      string
	ProjectID string
	UserID    string
}

func (q *Queries) MemberUpdateRole(ctx context.Context, arg MemberUpdateRoleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, memberUpdateRole, arg.Role, arg.ProjectID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
