// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type ApiToken struct {
	ID          string
	UserID      string
	Name        string
	TokenHash   string
	TokenPrefix string
	Scope       string
	ProjectID   *string
	LastUsedAt  *string
	RevokedAt   *string
	CreatedAt   string
}

type Comment struct {
	ID         string
	TicketID   string
	AuthorType string
	AuthorID   string
	Body       string
	CreatedAt  string
	EditedAt   *string
	DeletedAt  *string
}

type Label struct {
	ID        string
	ProjectID string
	Name      string
	Color     string
}

type Project struct {
	ID               string
	Key              string
	Name             string
	Description      string
	NextTicketNumber int64
	CreatedBy        string
	ArchivedAt       *string
	CreatedAt        string
	UpdatedAt        string
}

type ProjectMember struct {
	ProjectID string
	UserID    string
	Role      string
	CreatedAt string
}

type Session struct {
	TokenHash string
	UserID    string
	ExpiresAt string
	CreatedAt string
}

type Ticket struct {
	ID          string
	ProjectID   string
	Number      int64
	Title       string
	Description string
	Status      string
	Priority    string
	AssigneeID  *string
	Position    float64
	DueDate     *string
	DeletedAt   *string
	CreatedAt   string
	UpdatedAt   string
}

type TicketActivity struct {
	ID        string
	TicketID  string
	ActorType string
	ActorID   string
	Action    string
	Changes   string
	CreatedAt string
}

type TicketLabel struct {
	TicketID string
	LabelID  string
}

type User struct {
	ID           string
	Email        string
	DisplayName  string
	PasswordHash string
	CreatedAt    string
}
