// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"strings"
)

const projectDelete = `-- name: ProjectDelete :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) ProjectDelete(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, projectDelete, id)
	return err
}

const projectInsert = `-- name: ProjectInsert :one
INSERT INTO projects (id, key, name, description, next_ticket_number, created_by, created_at, updated_at)
VALUES (?, ?, ?, ?, 1, ?, ?, ?)
RETURNING id, "key", name, description, next_ticket_number, created_by, archived_at, created_at, updated_at
`

type ProjectInsertParams struct {
	ID          string
	Key         string
	Name        string
	Description string
	CreatedBy   string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) ProjectInsert(ctx context.Context, arg ProjectInsertParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, projectInsert,
		arg.ID,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.NextTicketNumber,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const projectInsertOwner = `-- name: ProjectInsertOwner :exec
INSERT INTO project_members (project_id, user_id, role, created_at)
VALUES (?, ?, 'owner', ?)
`

type ProjectInsertOwnerParams struct {
	ProjectID string
	UserID    string
	CreatedAt string
}

func (q *Queries) ProjectInsertOwner(ctx context.Context, arg ProjectInsertOwnerParams) error {
	_, err := q.db.ExecContext(ctx, projectInsertOwner, arg.ProjectID, arg.UserID, arg.CreatedAt)
	return err
}

const projectKeyExists = `-- name: ProjectKeyExists :one
SELECT EXISTS (SELECT 1 FROM projects WHERE key = ?)
`

func (q *Queries) ProjectKeyExists(ctx context.Context, key string) (bool, error) {
	row := q.db.QueryRowContext(ctx, projectKeyExists, key)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const projectListForUser = `-- name: ProjectListForUser :many
SELECT p.id, p.key, p.name, p.description, p.next_ticket_number, p.created_by,
       p.archived_at, p.created_at, p.updated_at, m.role AS member_role
FROM projects p
JOIN project_members m ON m.project_id = p.id AND m.user_id = ?1
WHERE (CAST(?2 AS INTEGER) = 1 OR p.archived_at IS NULL)
  AND (CAST(?3 AS TEXT) = '' OR p.id = CAST(?3 AS TEXT))
ORDER BY lower(p.name), p.key
`

type ProjectListForUserParams struct {
	UserID          string
	IncludeArchived int64
	OnlyProject     string
}

type ProjectListForUserRow struct {
	ID               string
	Key              string
	Name             string
	Description      string
	NextTicketNumber int64
	CreatedBy        string
	ArchivedAt       *string
	CreatedAt        string
	UpdatedAt        string
	MemberRole       string
}

// Member projects ordered by lower(name), then key. only_project (” = no limit) serves
// project-limited tokens; include_archived 0 hides archived projects.
func (q *Queries) ProjectListForUser(ctx context.Context, arg ProjectListForUserParams) ([]ProjectListForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, projectListForUser, arg.UserID, arg.IncludeArchived, arg.OnlyProject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectListForUserRow
	for rows.Next() {
		var i ProjectListForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.NextTicketNumber,
			&i.CreatedBy,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectStatusCounts = `-- name: ProjectStatusCounts :many
SELECT project_id, status, COUNT(*) AS n
FROM tickets
WHERE deleted_at IS NULL AND project_id IN (/*SLICE:project_ids*/?)
GROUP BY project_id, status
`

type ProjectStatusCountsRow struct {
	ProjectID string
	Status    string
	N         int64
}

// Live (not soft-deleted) ticket counts per project and status.
func (q *Queries) ProjectStatusCounts(ctx context.Context, projectIds []string) ([]ProjectStatusCountsRow, error) {
	query := projectStatusCounts
	var queryParams []interface{}
	if len(projectIds) > 0 {
		for _, v := range projectIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:project_ids*/?", strings.Repeat(",?", len(projectIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:project_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectStatusCountsRow
	for rows.Next() {
		var i ProjectStatusCountsRow
		if err := rows.Scan(&i.ProjectID, &i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectUpdate = `-- name: ProjectUpdate :one
UPDATE projects SET name = ?, description = ?, archived_at = ?, updated_at = ?
WHERE id = ?
RETURNING id, "key", name, description, next_ticket_number, created_by, archived_at, created_at, updated_at
`

type ProjectUpdateParams struct {
	Name        string
	Description string
	ArchivedAt  *string
	UpdatedAt   string
	ID          string
}

func (q *Queries) ProjectUpdate(ctx context.Context, arg ProjectUpdateParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, projectUpdate,
		arg.Name,
		arg.Description,
		arg.ArchivedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.NextTicketNumber,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
