// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// Login lookup. users.email is COLLATE NOCASE, so the match is case-insensitive.
	AccountGetCredentialsByEmail(ctx context.Context, email string) (AccountGetCredentialsByEmailRow, error)
	AccountGetPasswordHash(ctx context.Context, id string) (string, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSessionsForUserExcept(ctx context.Context, arg DeleteSessionsForUserExceptParams) (int64, error)
	GetAPIToken(ctx context.Context, id string) (ApiToken, error)
	// Resolves a project by id OR key together with the user's membership in one query.
	// Pass the ULID in ref_id (or "") and the uppercased key in ref_key (or "").
	// No row means unknown project and non-member alike.
	GetProjectForUser(ctx context.Context, arg GetProjectForUserParams) (GetProjectForUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListSessionHashesForUser(ctx context.Context, userID string) ([]string, error)
	ListUsersByIDs(ctx context.Context, ids []string) ([]User, error)
	// Owning ticket and project of a live comment on a live ticket.
	LocateComment(ctx context.Context, id string) (LocateCommentRow, error)
	LocateLabel(ctx context.Context, id string) (LocateLabelRow, error)
	// Owning project of a live (not soft-deleted) ticket.
	LocateTicketByID(ctx context.Context, id string) (LocateTicketByIDRow, error)
	// Same, by project key (uppercase) and ticket number.
	LocateTicketByRef(ctx context.Context, arg LocateTicketByRefParams) (LocateTicketByRefRow, error)
	SeedArchiveProject(ctx context.Context, arg SeedArchiveProjectParams) error
	SeedMember(ctx context.Context, arg SeedMemberParams) error
	// Direct inserts used by internal/testutil to seed data without going through services.
	SeedProject(ctx context.Context, arg SeedProjectParams) (Project, error)
	SessionDeleteAllForUser(ctx context.Context, userID string) (int64, error)
	SessionDeleteByHash(ctx context.Context, tokenHash string) (int64, error)
	// Timestamps are fixed-width text, so string comparison is chronological.
	SessionDeleteExpired(ctx context.Context, expiresAt string) (int64, error)
	SessionExtend(ctx context.Context, arg SessionExtendParams) (int64, error)
	// One session joined with its user. Expiry is judged by the caller (it owns the clock).
	SessionGetByHash(ctx context.Context, tokenHash string) (SessionGetByHashRow, error)
	TokenCountActive(ctx context.Context, userID string) (int64, error)
	// API token by the SHA-256 of its secret, with owner and (optional) limited project key.
	TokenGetByHash(ctx context.Context, tokenHash string) (TokenGetByHashRow, error)
	TokenGetForUser(ctx context.Context, arg TokenGetForUserParams) (TokenGetForUserRow, error)
	// Newest first, revoked included.
	TokenListForUser(ctx context.Context, userID string) ([]TokenListForUserRow, error)
	// Sets revoked_at only when still NULL. Rows affected is 1 for an existing own token even
	// when it was already revoked (idempotent), 0 for unknown or someone else's.
	TokenRevoke(ctx context.Context, arg TokenRevokeParams) (int64, error)
	// Stamps last_used_at only when never used or last used before the threshold (now minus 60 s).
	TokenTouch(ctx context.Context, arg TokenTouchParams) (int64, error)
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
