// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteSessionsForUserExcept(ctx context.Context, arg DeleteSessionsForUserExceptParams) (int64, error)
	GetAPIToken(ctx context.Context, id string) (ApiToken, error)
	// Resolves a project by id OR key together with the user's membership in one query.
	// Pass the ULID in ref_id (or "") and the uppercased key in ref_key (or "").
	// No row means unknown project and non-member alike.
	GetProjectForUser(ctx context.Context, arg GetProjectForUserParams) (GetProjectForUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListSessionHashesForUser(ctx context.Context, userID string) ([]string, error)
	ListUsersByIDs(ctx context.Context, ids []string) ([]User, error)
	// Owning ticket and project of a live comment on a live ticket.
	LocateComment(ctx context.Context, id string) (LocateCommentRow, error)
	LocateLabel(ctx context.Context, id string) (LocateLabelRow, error)
	// Owning project of a live (not soft-deleted) ticket.
	LocateTicketByID(ctx context.Context, id string) (LocateTicketByIDRow, error)
	// Same, by project key (uppercase) and ticket number.
	LocateTicketByRef(ctx context.Context, arg LocateTicketByRefParams) (LocateTicketByRefRow, error)
	SeedArchiveProject(ctx context.Context, arg SeedArchiveProjectParams) error
	SeedMember(ctx context.Context, arg SeedMemberParams) error
	// Direct inserts used by internal/testutil to seed data without going through services.
	SeedProject(ctx context.Context, arg SeedProjectParams) (Project, error)
	UpdateUserDisplayName(ctx context.Context, arg UpdateUserDisplayNameParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
