// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package db

import (
	"context"
)

const seedArchiveProject = `-- name: SeedArchiveProject :exec
UPDATE projects SET archived_at = ? WHERE id = ?
`

type SeedArchiveProjectParams struct {
	ArchivedAt *string
	ID         string
}

func (q *Queries) SeedArchiveProject(ctx context.Context, arg SeedArchiveProjectParams) error {
	_, err := q.db.ExecContext(ctx, seedArchiveProject, arg.ArchivedAt, arg.ID)
	return err
}

const seedMember = `-- name: SeedMember :exec
INSERT INTO project_members (project_id, user_id, role, created_at)
VALUES (?, ?, ?, ?)
`

type SeedMemberParams struct {
	ProjectID string
	UserID    string
	Role      string
	CreatedAt string
}

func (q *Queries) SeedMember(ctx context.Context, arg SeedMemberParams) error {
	_, err := q.db.ExecContext(ctx, seedMember,
		arg.ProjectID,
		arg.UserID,
		arg.Role,
		arg.CreatedAt,
	)
	return err
}

const seedProject = `-- name: SeedProject :one

INSERT INTO projects (id, key, name, description, next_ticket_number, created_by, created_at, updated_at)
VALUES (?, ?, ?, '', 1, ?, ?, ?)
RETURNING id, "key", name, description, next_ticket_number, created_by, archived_at, created_at, updated_at
`

type SeedProjectParams struct {
	ID        string
	Key       string
	Name      string
	CreatedBy string
	CreatedAt string
	UpdatedAt string
}

// Direct inserts used by internal/testutil to seed data without going through services.
func (q *Queries) SeedProject(ctx context.Context, arg SeedProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, seedProject,
		arg.ID,
		arg.Key,
		arg.Name,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.NextTicketNumber,
		&i.CreatedBy,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
