// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
)

const sessionDeleteAllForUser = `-- name: SessionDeleteAllForUser :execrows
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) SessionDeleteAllForUser(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, sessionDeleteAllForUser, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sessionDeleteByHash = `-- name: SessionDeleteByHash :execrows
DELETE FROM sessions WHERE token_hash = ?
`

func (q *Queries) SessionDeleteByHash(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, sessionDeleteByHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sessionDeleteExpired = `-- name: SessionDeleteExpired :execrows
DELETE FROM sessions WHERE expires_at <= ?
`

// Timestamps are fixed-width text, so string comparison is chronological.
func (q *Queries) SessionDeleteExpired(ctx context.Context, expiresAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, sessionDeleteExpired, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sessionExtend = `-- name: SessionExtend :execrows
UPDATE sessions SET expires_at = ? WHERE token_hash = ?
`

type SessionExtendParams struct {
	ExpiresAt string
	TokenHash string
}

func (q *Queries) SessionExtend(ctx context.Context, arg SessionExtendParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, sessionExtend, arg.ExpiresAt, arg.TokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sessionGetByHash = `-- name: SessionGetByHash :one
SELECT s.token_hash, s.user_id, s.expires_at, s.created_at,
       u.email, u.display_name, u.created_at AS user_created_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = ?
`

type SessionGetByHashRow struct {
	TokenHash     string
	UserID        string
	ExpiresAt     string
	CreatedAt     string
	Email         string
	DisplayName   string
	UserCreatedAt string
}

// One session joined with its user. Expiry is judged by the caller (it owns the clock).
func (q *Queries) SessionGetByHash(ctx context.Context, tokenHash string) (SessionGetByHashRow, error) {
	row := q.db.QueryRowContext(ctx, sessionGetByHash, tokenHash)
	var i SessionGetByHashRow
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Email,
		&i.DisplayName,
		&i.UserCreatedAt,
	)
	return i, err
}
