// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package db

import (
	"context"
	"strings"
)

const ticketAddLabel = `-- name: TicketAddLabel :exec
INSERT INTO ticket_labels (ticket_id, label_id) VALUES (?, ?)
`

type TicketAddLabelParams struct {
	TicketID string
	LabelID  string
}

func (q *Queries) TicketAddLabel(ctx context.Context, arg TicketAddLabelParams) error {
	_, err := q.db.ExecContext(ctx, ticketAddLabel, arg.TicketID, arg.LabelID)
	return err
}

const ticketAllocateNumber = `-- name: TicketAllocateNumber :one

UPDATE projects SET next_ticket_number = next_ticket_number + 1
WHERE id = ?
RETURNING next_ticket_number - 1 AS number
`

// Ticket queries. Every name carries the Ticket prefix (names are global across all .sql files).
// Atomic per-project counter; runs inside the create transaction.
func (q *Queries) TicketAllocateNumber(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, ticketAllocateNumber, id)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const ticketClearLabels = `-- name: TicketClearLabels :exec
DELETE FROM ticket_labels WHERE ticket_id = ?
`

func (q *Queries) TicketClearLabels(ctx context.Context, ticketID string) error {
	_, err := q.db.ExecContext(ctx, ticketClearLabels, ticketID)
	return err
}

const ticketCommentCounts = `-- name: TicketCommentCounts :many
SELECT ticket_id, COUNT(*) AS comment_count FROM comments
WHERE ticket_id IN (/*SLICE:ticket_ids*/?) AND deleted_at IS NULL
GROUP BY ticket_id
`

type TicketCommentCountsRow struct {
	TicketID     string
	CommentCount int64
}

// Batched comment counts (non-deleted comments only).
func (q *Queries) TicketCommentCounts(ctx context.Context, ticketIds []string) ([]TicketCommentCountsRow, error) {
	query := ticketCommentCounts
	var queryParams []interface{}
	if len(ticketIds) > 0 {
		for _, v := range ticketIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ticket_ids*/?", strings.Repeat(",?", len(ticketIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ticket_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketCommentCountsRow
	for rows.Next() {
		var i TicketCommentCountsRow
		if err := rows.Scan(&i.TicketID, &i.CommentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ticketGet = `-- name: TicketGet :one
SELECT id, project_id, number, title, description, status, priority, assignee_id, position, due_date, deleted_at, created_at, updated_at FROM tickets WHERE id = ? AND deleted_at IS NULL
`

// A live (not soft-deleted) ticket by id.
func (q *Queries) TicketGet(ctx context.Context, id string) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, ticketGet, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.Position,
		&i.DueDate,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ticketInsert = `-- name: TicketInsert :exec
INSERT INTO tickets (id, project_id, number, title, description, status, priority, assignee_id, position, due_date, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type TicketInsertParams struct {
	ID          string
	ProjectID   string
	Number      int64
	Title       string
	Description string
	Status      string
	Priority    string
	AssigneeID  *string
	Position    float64
	DueDate     *string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) TicketInsert(ctx context.Context, arg TicketInsertParams) error {
	_, err := q.db.ExecContext(ctx, ticketInsert,
		arg.ID,
		arg.ProjectID,
		arg.Number,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.AssigneeID,
		arg.Position,
		arg.DueDate,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const ticketIsMember = `-- name: TicketIsMember :one
SELECT COUNT(*) FROM project_members WHERE project_id = ? AND user_id = ?
`

type TicketIsMemberParams struct {
	ProjectID string
	UserID    string
}

func (q *Queries) TicketIsMember(ctx context.Context, arg TicketIsMemberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, ticketIsMember, arg.ProjectID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const ticketLabelsForTickets = `-- name: TicketLabelsForTickets :many
SELECT tl.ticket_id, l.id, l.project_id, l.name, l.color
FROM ticket_labels tl JOIN labels l ON l.id = tl.label_id
WHERE tl.ticket_id IN (/*SLICE:ticket_ids*/?)
ORDER BY tl.ticket_id, l.name, l.id
`

type TicketLabelsForTicketsRow struct {
	TicketID  string
	ID        string
	ProjectID string
	Name      string
	Color     string
}

// Batched label hydration (name order via the NOCASE column collation, then id).
func (q *Queries) TicketLabelsForTickets(ctx context.Context, ticketIds []string) ([]TicketLabelsForTicketsRow, error) {
	query := ticketLabelsForTickets
	var queryParams []interface{}
	if len(ticketIds) > 0 {
		for _, v := range ticketIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ticket_ids*/?", strings.Repeat(",?", len(ticketIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ticket_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketLabelsForTicketsRow
	for rows.Next() {
		var i TicketLabelsForTicketsRow
		if err := rows.Scan(
			&i.TicketID,
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ticketLabelsInProject = `-- name: TicketLabelsInProject :many
SELECT id, project_id, name, color FROM labels
WHERE project_id = ?1 AND id IN (/*SLICE:label_ids*/?)
ORDER BY name, id
`

type TicketLabelsInProjectParams struct {
	ProjectID string
	LabelIds  []string
}

// Labels of one project among the given ids, in name order (validates ownership and gives names).
func (q *Queries) TicketLabelsInProject(ctx context.Context, arg TicketLabelsInProjectParams) ([]Label, error) {
	query := ticketLabelsInProject
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ProjectID)
	if len(arg.LabelIds) > 0 {
		for _, v := range arg.LabelIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:label_ids*/?", strings.Repeat(",?", len(arg.LabelIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:label_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ticketListColumn = `-- name: TicketListColumn :many
SELECT id, position FROM tickets
WHERE project_id = ?1 AND status = ?2 AND deleted_at IS NULL
  AND id <> ?3
ORDER BY position, id
`

type TicketListColumnParams struct {
	ProjectID string
	Status    string
	ExcludeID string
}

type TicketListColumnRow struct {
	ID       string
	Position float64
}

// Live tickets of one column in (position, id) order, excluding one ticket id (” excludes none).
func (q *Queries) TicketListColumn(ctx context.Context, arg TicketListColumnParams) ([]TicketListColumnRow, error) {
	rows, err := q.db.QueryContext(ctx, ticketListColumn, arg.ProjectID, arg.Status, arg.ExcludeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketListColumnRow
	for rows.Next() {
		var i TicketListColumnRow
		if err := rows.Scan(&i.ID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ticketListPage = `-- name: TicketListPage :many
SELECT t.id, t.project_id, t.number, t.title, t.status, t.priority, t.assignee_id, t.position,
       t.due_date, t.created_at, t.updated_at,
       CAST(CASE t.status WHEN 'backlog' THEN 0 WHEN 'todo' THEN 1 WHEN 'in_progress' THEN 2 ELSE 3 END AS INTEGER) AS status_rank
FROM tickets t
WHERE t.project_id = ?1 AND t.deleted_at IS NULL
  AND (CAST(?2 AS TEXT) IS NULL OR t.status = CAST(?2 AS TEXT))
  AND (CAST(?3 AS TEXT) IS NULL OR t.priority = CAST(?3 AS TEXT))
  AND (CAST(?4 AS INTEGER) = 0 OR t.assignee_id IS NULL)
  AND (CAST(?5 AS TEXT) IS NULL OR t.assignee_id = CAST(?5 AS TEXT))
  AND (CAST(?6 AS TEXT) IS NULL OR EXISTS (
        SELECT 1 FROM ticket_labels tl WHERE tl.ticket_id = t.id AND tl.label_id = CAST(?6 AS TEXT)))
  AND (CAST(?7 AS TEXT) IS NULL
       OR instr(lower(t.title), lower(CAST(?7 AS TEXT))) > 0
       OR instr(lower(t.description), lower(CAST(?7 AS TEXT))) > 0)
  AND (CAST(?8 AS INTEGER) = 0
       OR CASE t.status WHEN 'backlog' THEN 0 WHEN 'todo' THEN 1 WHEN 'in_progress' THEN 2 ELSE 3 END > CAST(?9 AS INTEGER)
       OR (CASE t.status WHEN 'backlog' THEN 0 WHEN 'todo' THEN 1 WHEN 'in_progress' THEN 2 ELSE 3 END = CAST(?9 AS INTEGER)
           AND t.position > CAST(?10 AS REAL))
       OR (CASE t.status WHEN 'backlog' THEN 0 WHEN 'todo' THEN 1 WHEN 'in_progress' THEN 2 ELSE 3 END = CAST(?9 AS INTEGER)
           AND t.position = CAST(?10 AS REAL)
           AND t.id > CAST(?11 AS TEXT)))
ORDER BY status_rank, t.position, t.id
LIMIT ?12
`

type TicketListPageParams struct {
	ProjectID      string
	Status         *string
	Priority       *string
	Unassigned     int64
	AssigneeID     *string
	LabelID        *string
	QueryText      *string
	HasCursor      int64
	CursorRank     int64
	CursorPosition float64
	CursorID       string
	RowLimit       int64
}

type TicketListPageRow struct {
	ID         string
	ProjectID  string
	Number     int64
	Title      string
	Status     string
	Priority   string
	AssigneeID *string
	Position   float64
	DueDate    *string
	CreatedAt  string
	UpdatedAt  string
	StatusRank int64
}

// Board order: status rank, position, id. Keyset predicate in expanded OR form (no row values).
// description is intentionally not selected. query_text is a literal substring (instr, so no
// LIKE wildcards to escape; lower() is ASCII-only, as the spec accepts).
func (q *Queries) TicketListPage(ctx context.Context, arg TicketListPageParams) ([]TicketListPageRow, error) {
	rows, err := q.db.QueryContext(ctx, ticketListPage,
		arg.ProjectID,
		arg.Status,
		arg.Priority,
		arg.Unassigned,
		arg.AssigneeID,
		arg.LabelID,
		arg.QueryText,
		arg.HasCursor,
		arg.CursorRank,
		arg.CursorPosition,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketListPageRow
	for rows.Next() {
		var i TicketListPageRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Number,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.AssigneeID,
			&i.Position,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StatusRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ticketSeedGetRaw = `-- name: TicketSeedGetRaw :one
SELECT id, project_id, number, title, description, status, priority, assignee_id, position, due_date, deleted_at, created_at, updated_at FROM tickets WHERE id = ?
`

// Test only: a ticket row including soft-deleted ones.
func (q *Queries) TicketSeedGetRaw(ctx context.Context, id string) (Ticket, error) {
	row := q.db.QueryRowContext(ctx, ticketSeedGetRaw, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.AssigneeID,
		&i.Position,
		&i.DueDate,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ticketSeedLabel = `-- name: TicketSeedLabel :one
INSERT INTO labels (id, project_id, name, color) VALUES (?, ?, ?, ?)
RETURNING id, project_id, name, color
`

type TicketSeedLabelParams struct {
	ID        string
	ProjectID string
	Name      string
	Color     string
}

// Test seeding only: a label without going through the Labels service.
func (q *Queries) TicketSeedLabel(ctx context.Context, arg TicketSeedLabelParams) (Label, error) {
	row := q.db.QueryRowContext(ctx, ticketSeedLabel,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Color,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
	)
	return i, err
}

const ticketSetPosition = `-- name: TicketSetPosition :exec
UPDATE tickets SET position = ? WHERE id = ?
`

type TicketSetPositionParams struct {
	Position float64
	ID       string
}

// Renumbering: position only, no updated_at bump.
func (q *Queries) TicketSetPosition(ctx context.Context, arg TicketSetPositionParams) error {
	_, err := q.db.ExecContext(ctx, ticketSetPosition, arg.Position, arg.ID)
	return err
}

const ticketSoftDelete = `-- name: TicketSoftDelete :execrows
UPDATE tickets SET deleted_at = ?, updated_at = ? WHERE id = ? AND deleted_at IS NULL
`

type TicketSoftDeleteParams struct {
	DeletedAt *string
	UpdatedAt string
	ID        string
}

func (q *Queries) TicketSoftDelete(ctx context.Context, arg TicketSoftDeleteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, ticketSoftDelete, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ticketUpdateFields = `-- name: TicketUpdateFields :exec
UPDATE tickets
SET title = ?1, description = ?2, priority = ?3,
    due_date = ?4, assignee_id = ?5, updated_at = ?6
WHERE id = ?7
`

type TicketUpdateFieldsParams struct {
	Title       string
	Description string
	Priority    string
	DueDate     *string
	AssigneeID  *string
	UpdatedAt   string
	ID          string
}

func (q *Queries) TicketUpdateFields(ctx context.Context, arg TicketUpdateFieldsParams) error {
	_, err := q.db.ExecContext(ctx, ticketUpdateFields,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.DueDate,
		arg.AssigneeID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const ticketUpdateMove = `-- name: TicketUpdateMove :exec
UPDATE tickets SET status = ?, position = ?, updated_at = ? WHERE id = ?
`

type TicketUpdateMoveParams struct {
	Status    string
	Position  float64
	UpdatedAt string
	ID        string
}

func (q *Queries) TicketUpdateMove(ctx context.Context, arg TicketUpdateMoveParams) error {
	_, err := q.db.ExecContext(ctx, ticketUpdateMove,
		arg.Status,
		arg.Position,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const ticketUsersByIDs = `-- name: TicketUsersByIDs :many
SELECT id, email, display_name FROM users WHERE id IN (/*SLICE:user_ids*/?)
`

type TicketUsersByIDsRow struct {
	ID          string
	Email       string
	DisplayName string
}

// Batched assignee hydration.
func (q *Queries) TicketUsersByIDs(ctx context.Context, userIds []string) ([]TicketUsersByIDsRow, error) {
	query := ticketUsersByIDs
	var queryParams []interface{}
	if len(userIds) > 0 {
		for _, v := range userIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:user_ids*/?", strings.Repeat(",?", len(userIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:user_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketUsersByIDsRow
	for rows.Next() {
		var i TicketUsersByIDsRow
		if err := rows.Scan(&i.ID, &i.Email, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
