// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package db

import (
	"context"
)

const tokenCountActive = `-- name: TokenCountActive :one
SELECT COUNT(*) FROM api_tokens WHERE user_id = ? AND revoked_at IS NULL
`

func (q *Queries) TokenCountActive(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, tokenCountActive, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const tokenGetByHash = `-- name: TokenGetByHash :one
SELECT t.id, t.user_id, t.name, t.token_prefix, t.scope, t.project_id, t.last_used_at, t.revoked_at, t.created_at,
       t.token_hash,
       u.email AS owner_email, u.display_name AS owner_display_name, u.created_at AS owner_created_at,
       p.key AS project_key
FROM api_tokens t
JOIN users u ON u.id = t.user_id
LEFT JOIN projects p ON p.id = t.project_id
WHERE t.token_hash = ?
`

type TokenGetByHashRow struct {
	ID               string
	UserID           string
	Name             string
	TokenPrefix      string
	Scope            string
	ProjectID        *string
	LastUsedAt       *string
	RevokedAt        *string
	CreatedAt        string
	TokenHash        string
	OwnerEmail       string
	OwnerDisplayName string
	OwnerCreatedAt   string
	ProjectKey       *string
}

// API token by the SHA-256 of its secret, with owner and (optional) limited project key.
func (q *Queries) TokenGetByHash(ctx context.Context, tokenHash string) (TokenGetByHashRow, error) {
	row := q.db.QueryRowContext(ctx, tokenGetByHash, tokenHash)
	var i TokenGetByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenPrefix,
		&i.Scope,
		&i.ProjectID,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.TokenHash,
		&i.OwnerEmail,
		&i.OwnerDisplayName,
		&i.OwnerCreatedAt,
		&i.ProjectKey,
	)
	return i, err
}

const tokenGetForUser = `-- name: TokenGetForUser :one
SELECT t.id, t.user_id, t.name, t.token_prefix, t.scope, t.project_id, t.last_used_at, t.revoked_at, t.created_at,
       p.key AS project_key
FROM api_tokens t
LEFT JOIN projects p ON p.id = t.project_id
WHERE t.id = ? AND t.user_id = ?
`

type TokenGetForUserParams struct {
	ID     string
	UserID string
}

type TokenGetForUserRow struct {
	ID          string
	UserID      string
	Name        string
	TokenPrefix string
	Scope       string
	ProjectID   *string
	LastUsedAt  *string
	RevokedAt   *string
	CreatedAt   string
	ProjectKey  *string
}

func (q *Queries) TokenGetForUser(ctx context.Context, arg TokenGetForUserParams) (TokenGetForUserRow, error) {
	row := q.db.QueryRowContext(ctx, tokenGetForUser, arg.ID, arg.UserID)
	var i TokenGetForUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenPrefix,
		&i.Scope,
		&i.ProjectID,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.ProjectKey,
	)
	return i, err
}

const tokenListForUser = `-- name: TokenListForUser :many
SELECT t.id, t.user_id, t.name, t.token_prefix, t.scope, t.project_id, t.last_used_at, t.revoked_at, t.created_at,
       p.key AS project_key
FROM api_tokens t
LEFT JOIN projects p ON p.id = t.project_id
WHERE t.user_id = ?
ORDER BY t.created_at DESC, t.id DESC
`

type TokenListForUserRow struct {
	ID          string
	UserID      string
	Name        string
	TokenPrefix string
	Scope       string
	ProjectID   *string
	LastUsedAt  *string
	RevokedAt   *string
	CreatedAt   string
	ProjectKey  *string
}

// Newest first, revoked included.
func (q *Queries) TokenListForUser(ctx context.Context, userID string) ([]TokenListForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, tokenListForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TokenListForUserRow
	for rows.Next() {
		var i TokenListForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenPrefix,
			&i.Scope,
			&i.ProjectID,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.ProjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tokenRevoke = `-- name: TokenRevoke :execrows
UPDATE api_tokens SET revoked_at = COALESCE(revoked_at, ?) WHERE id = ? AND user_id = ?
`

type TokenRevokeParams struct {
	RevokedAt *string
	ID        string
	UserID    string
}

// Sets revoked_at only when still NULL. Rows affected is 1 for an existing own token even
// when it was already revoked (idempotent), 0 for unknown or someone else's.
func (q *Queries) TokenRevoke(ctx context.Context, arg TokenRevokeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, tokenRevoke, arg.RevokedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const tokenTouch = `-- name: TokenTouch :execrows
UPDATE api_tokens SET last_used_at = ?1
WHERE id = ?2 AND (last_used_at IS NULL OR last_used_at < ?3)
`

type TokenTouchParams struct {
	Now       *string
	ID        string
	Threshold *string
}

// Stamps last_used_at only when never used or last used before the threshold (now minus 60 s).
func (q *Queries) TokenTouch(ctx context.Context, arg TokenTouchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, tokenTouch, arg.Now, arg.ID, arg.Threshold)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
